version: '3.9'

services:
  db:
    image: postgres:15
    container_name: notes-java
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: